Repository wecode-bootcamp-korea/29-2nd-GREAM-frontend, pull requests merged in 2022-02, with the labels that each got.

#3 [Feature/productDetailCarousel] 상세페이지 캐러셀이미지 구현
  package-lock.json
  package.json
  public/data/product.json
  public/images/jihong/Img_1.jpg
  public/images/jihong/Img_2.jpg
  public/images/jihong/Img_3.jpg
  public/images/jihong/arrow_left.svg
  public/images/jihong/arrow_right.svg
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailSlider.js
Labels: Status: 리뷰 요청

#5 [feature/theme] 공용 style 속성, 라이브러리, 이미지 추가
  package-lock.json
  package.json
  public/images/favicon.jpg
  public/images/favicon2.jpg
  public/index.html
  src/styles/mixin.js
  src/styles/theme.js
Labels: Status: Accepted

#4 [Feature/productDetailInfo] 상세페이지 상품 정보 상단 레이아웃
  package-lock.json
  package.json
  public/data/Products.json
  src/index.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailInfo/Button.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/DeliveryBox/DeliveryBox.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/DeliveryBox/ShippingInfo.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/DetailDesc.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/InBox.js
  src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalContents.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalTop.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/PurchaseBtn.js
Labels: Status: 리뷰 요청

#6 [Feature/favoritesBtn] 관심상품 담기 버튼 생성 및 모달
  package-lock.json
  package.json
  public/data/product.json
  src/pages/ProductDetail/FavoriteBtn.js
  src/pages/ProductDetail/FavoriteModal.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailSlider.js
Labels: Status: 리뷰 요청

#2 [Feature/login] 로그인 모달창 레이아웃 생성
  .gitignore
  public/images/Login/kakao_login_large_wide.png
  public/images/Login/logo.png
  src/Router.js
  src/components/Nav/Login/Login.js
  src/components/Nav/Login/OauthHandler.js
  src/components/Nav/Nav.js
  src/pages/ProductsList/ProductsListComponents/Login.js
Labels: Status: 리뷰 요청

#8 [Feature/products list] 레이아웃 및 이미지 슬라이드
  .vscode/extensions.json
  package-lock.json
  public/data/ProductCard.json
  public/data/data.json
  public/images/banner_img1.jpeg
  public/images/banner_img2.jpeg
  public/images/banner_img3.jpeg
  public/images/picture.jpg
  public/images/반고흐.webp
  public/images/잭슨폴록.jpeg
  src/components/ProductCard/ProductCard.js
  src/pages/ProductsList/ProductsList.js
  src/pages/ProductsList/ProductsListComponents/Author.js
  src/pages/ProductsList/ProductsListComponents/Box.js
  src/pages/ProductsList/ProductsListComponents/FILTER_LIST.js
  src/pages/ProductsList/ProductsListComponents/LeftFilter.js
  src/pages/ProductsList/ProductsListComponents/Listwrap.js
  src/pages/ProductsList/ProductsListComponents/Login.js
  src/pages/ProductsList/ProductsListComponents/RightFilter.js
  src/pages/ProductsList/ProductsListComponents/SLIDER_DATAS.js
  src/pages/ProductsList/ProductsListComponents/Sliders.js
Labels: Status: 리뷰 요청

#11 [feature/loginKakao] Add: Post Kakao login authorize code to server
  src/components/Nav/Login/Login.js
  src/components/Nav/Login/OauthHandler.js
  src/components/Nav/Nav.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [29기 박혜린] 상세페이지 모달창 컴포넌트 개별화 작업 및 제품 사이즈 별 가격 담기 기능 구현
  src/Router.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailInfo/Button.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/InBox.js
  src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalContents.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalTop.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/PurchaseBtn.js
Labels: Status: 리뷰 요청

#10 [Feature/MarketPriceModal] 시세 모달창 구현
  package-lock.json
  package.json
  src/Router.js
  src/pages/ProductDetail/FavoriteModal.js
  src/pages/ProductDetail/MarketPrice.js
  src/pages/ProductDetail/MarketPriceModal.js
  src/pages/ProductDetail/MarketPriceTable.js
  src/pages/ProductDetail/MarketPriceTableGroup.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/confirmInfo.js
  src/pages/ProductDetail/sizeInfo2.js
Labels: Status: Conflict 해결 요청, Status: 도움 요청

#12 [feature/nav] Add: Nav Area & SearchBar
  src/components/Nav/Nav.js
  src/components/Nav/SearchBar/SearchBar.js
Labels: Status: 리뷰 요청

#15 [Feature/filter] Add: 메인페이지 css 레이아웃 수정 및 분류버튼 생성
  package-lock.json
  package.json
  public/images/jihong/dowoon.jpg
  public/images/jihong/gangil.jpg
  public/images/jihong/hyelynn.jpg
  public/images/jihong/jaehyung.jpg
  public/images/jihong/jihong.jpg
  public/images/jihong/kyungwon.jpg
  src/components/ProductCard/ProductCard.js
  src/pages/ProductsList/ProductsList.js
  src/pages/ProductsList/ProductsListComponents/DROPDOWN_LIST.js
  src/pages/ProductsList/ProductsListComponents/LeftFilter.js
  src/pages/ProductsList/ProductsListComponents/Listwrap.js
  src/pages/ProductsList/ProductsListComponents/RightFilter.js
  src/pages/ProductsList/ProductsListComponents/SLIDER_DATAS.js
  src/pages/ProductsList/ProductsListComponents/Sliders.js
  src/pages/ProductsList/ProductsListComponents/sortListBtn.js
Labels: Status: 리뷰 요청

#16 [Feature/product price chart] - 시세 차트 구현
  package-lock.json
  package.json
  src/Router.js
  src/pages/ProductDetail/PriceChart/Chart.js
  src/pages/ProductDetail/PriceChart/ChartBox.js
  src/pages/ProductDetail/PriceChart/ChartBtn.js
  src/pages/ProductDetail/PriceChart/PriceChart.js
Labels: Status: 리뷰 요청

#17 Add: navigate page after login
  src/Router.js
  src/components/Nav/Login/Logout.js
  src/components/Nav/Login/OauthHandler.js
  src/components/Nav/Nav.js
  src/config.js
Labels: Status: 리뷰 요청

#19 [feature / detailBtn] 상세 페이지 : 스크롤 시 show 되는 sticky 버튼 구현
  src/Router.js
  src/pages/ProductDetail/ProductDetailInfo/DetailBtn/StickyBtn.js
  src/pages/ProductDetail/ProductDetailInfo/DetailBtn/StickyBtnBox.js
Labels: Status: 리뷰 요청

#21 [Feature/product detail info] - 상세페이지 정보파트 최종 수정
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/DetailDesc.js
  src/pages/ProductDetail/ProductDetailInfo/DetailDesc/InBox.js
  src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalContents.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/ModalTop.js
Labels: Status: 리뷰 요청

#22 [Feature/product detail info] - 최종 수정
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
  src/pages/ProductDetail/ProductDetailInfo/PurchaseModal/PurchaseBtn.js
Labels: Status: 리뷰 요청

#25 [Feature/loginNavigate]Modify: fix product page link
  src/components/Nav/SearchBar/SearchBar.js
Labels: Status: 리뷰 요청

#26 [feature/productDetailInfo] rebase
  src/pages/ProductDetail/ProductDetailInfo/ProductDetailInfo.js
Labels: Status: 리뷰 요청
